name: Staging-Deploy

on:
    push:
        branches: [ staging ]

jobs:
    Staging-Deploy:

        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
            
            -   name: Set Node.js 18.17.1
                uses: actions/setup-node@v3
                with:
                    node-version: 18.17.1
            
            -   name: YARN install / export
                run: yarn install && yarn export && ls -la && pwd && whoami
            
            -   name: SSH connection && git pull
                uses: appleboy/ssh-action@v1.0.0
                with:
                    host: ${{ secrets.STAGING_HOST }}
                    username: ${{ secrets.STAGING_USER }}
                    key: ${{ secrets.STAGING_SSH_KEY }}
                    port: ${{ secrets.STAGING_PORT }}
                    script: |
                        cd /var/www/pianos-prelude-staging
                        git switch staging
                        git pull
                        rm -rf out/
                        ls -la

